%{?!ros_distro:%global ros_distro jazzy}
%global pkg_name ros2_pulse
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-jazzy-ros2-pulse
Version:        0.4.1
Release:        2%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Near-zero-overhead ROS 2 probe for per-topic message frequency and active-node
liveness, covering both inter-process and intra-process traffic. Works on stock
ROS 2 binaries via an LD_PRELOAD shim over the tracetools instrumentation layer:
no patched rmw_implementation, no ROS recompile, no privileges, and no DDS
traffic.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Near-zero-overhead ROS 2 probe for per-topic message frequency and active-node
liveness, covering both inter-process and intra-process traffic. Works on stock
ROS 2 binaries via an LD_PRELOAD shim over the tracetools instrumentation layer:
no patched rmw_implementation, no ROS recompile, no privileges, and no DDS
traffic.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Near-zero-overhead ROS 2 probe for per-topic message frequency and active-node
liveness, covering both inter-process and intra-process traffic. Works on stock
ROS 2 binaries via an LD_PRELOAD shim over the tracetools instrumentation layer:
no patched rmw_implementation, no ROS recompile, no privileges, and no DDS
traffic.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Mon Aug 24 2026 Tanay Kedia <95276223+TanayK07@users.noreply.github.com> - 0.4.1-2
- Autogenerated by Bloom
